name: pvmesh
channels:
  - conda-forge  
  - defaults
dependencies:
  # Dependencies should be kept as loosely pinned to version numbers as possible
  - alive-progress
  - black
  - jsonschema
  - jupyter
  - matplotlib
  - numba
  - pandas
  - pytest
  - python-gmsh
  - pyyaml
  - scipy
  - snakeviz
  - sphinx
  - tqdm
  - pip
  - pyqt
  - pyqt5-sip 
  - tk
  - pip:
    - sphinx-rtd-theme
    - sphinxcontrib.datatemplates
    #  - pip:
    #    - sphinx-rtd-theme
    #    - sphinxcontrib.datatemplates
    #    - -e . # Installs the pvade package
